### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by linuxman** [neofutur/gwgd#2]
Hello,

Is there any API documentation?, I have an installation of Stikked and when I make a short URL is not formed correctly.

Stikked me back a URL similar to this:

```
http://gw.gd/QJho<br /> <b>Notice</b>: Undefined index: HTTP_AC
```

Not sure if the problem is gw.gd or stikked. Is why I ask if they have made changes to the API gw.gd.

Greetings.

**Comment by claudehohl** [comment]
Hi Neofutur,

We have indeed a problem with the url shortener. It says:

$ curl http://gw.gd/api.php?long=http://bla
http://gw.gd/JEvB<br />
<b>Notice</b>:  Undefined index: HTTP_ACCEPT_ENCODING in <b>/home2/virtuals/gw.gd/html/inc/Casimir.php</b> on line <b>341</b><br />

Reference: https://github.com/claudehohl/Stikked/issues/50

**Comment by neofutur** [comment]
should be fixed in latest
